### PR TITLE
fix issue #6 - problem with flux example

### PR DESCRIPTION
**Pull request by JavascriptMick**
as per comment by weske, typo in controller method.
https://github.com/FormidableLabs/react-flux-concepts/issues/6

### CODE REVIEW

**Comment by timbuckley** [comment]
+1 on this. `006-flux.html` file does not operate with existing typo.

**Comment by colinmegill** [comment]
@ryan-roemer I'm not sure why I can't merge this - is there a permissions issue? I can push to this repo but see: 

screenshot 2015-03-15 21 59 00

**Comment by ryan-roemer** [comment]
@colinmegill -- Make sure you're logged in to GitHub. All of formidable has full access for this repo. Ping me if things still don't work and we can investigate your user account more specifically to see what's up.

**Comment by alejandronanez** [comment]
+1 @mdausmann.

**Comment by jeffwesson** [comment]
:+1:

**Comment by messa** [comment]
+1

**Pull request merged**
